version: "3.8"

services:
  backend:
    build:
      context: ./minivault-api
    container_name: minivault-api
    ports:
      - "8000:8000"
    environment:
      - ALLOW_ORIGINS=http://localhost:3000
    volumes:
      - ./minivault-api/logs:/app/logs
    restart: unless-stopped

  frontend:
    build:
      context: ./minivault-ui
    container_name: minivault-ui
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
